### PR TITLE
modify bash-commands to support other OS dylibs

### PR DESCRIPTION
**Pull request by arroadie**
This allows asdf to link the dylibs for other plafroms besides OSX.

```shell
# thiago @ SeaMonkey in ~/Projects/gamedev/asdf-haxe on git:master o [10:08:39] 
$ asdf haxe neko dylibs which
4.1.3

# thiago @ SeaMonkey in ~/Projects/gamedev/asdf-haxe on git:master o [10:10:00] 
$ asdf haxe neko dylibs unlink
removed '/home/thiago/.asdf/installs/haxe/4.1.3/bin/libneko.so'

# thiago @ SeaMonkey in ~/Projects/gamedev/asdf-haxe on git:master o [10:10:07] 
$ asdf haxe neko dylibs link  
'/home/thiago/.asdf/installs/haxe/4.1.3/bin/libneko.so' -> '/home/thiago/.asdf/installs/neko/2.3.0/bin/libneko.so'

# thiago @ SeaMonkey in ~/Projects/gamedev/asdf-haxe on git:master o [10:10:10] 
$ asdf haxe neko dylibs which 
4.1.3
```

### CODE REVIEW

**Comment by smorimoto** [comment]
This looks good overall. It will be possible to merge after the problem indicated by CI is fixed.

**Comment by arroadie** [comment]
Checking on it right now. Brb with the format changes :)
Thanks for checking it promptly!

**Comment by arroadie** [comment]
Please hold merging this as there's a problem with the symlinked so's. Will fix it and update the PR

**Comment by arroadie** [comment]
It was pretty straight forward. Not it's working as expected.

**Comment by smorimoto** [comment]
I don't follow the cause deeply, but it seems there is still a problem.

**Comment by arroadie** [comment]
Excellent, I'll take a look at it. Thanks for checking

**Comment by arroadie** [comment]
Don't seem to be able to reproduce the workflow issue on the latest ubuntu container

```
# thiago @ SeaMonkey in ~ [17:56:11] 
$ docker run -it --rm ubuntu
root@05457de92892:/# apt -qq update
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@05457de92892:/# apt -qq -y install curl git > /dev/null

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

debconf: delaying package configuration, since apt-utils is not installed
root@05457de92892:/# cd /root/            
root@05457de92892:~# git clone --depth 1 --branch master https://github.com/asdf-vm/asdf.git .asdf
Cloning into '.asdf'...
remote: Enumerating objects: 137, done.
remote: Counting objects: 100% (137/137), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 137 (delta 7), reused 53 (delta 1), pack-reused 0
Receiving objects: 100% (137/137), 77.59 KiB | 8.62 MiB/s, done.
Resolving deltas: 100% (7/7), done.
root@05457de92892:~# . .asdf/
.editorconfig      LICENSE            asdf.sh            help.txt
.git/              README.md          ballad-of-asdf.md  lib/
.github/           SECURITY.md        bin/               lint.sh
.gitignore         VERSION            completions/       release/
CHANGELOG.md       Vagrantfile        defaults           test/
CONTRIBUTING.md    asdf.fish          docs/              
root@05457de92892:~# . .asdf/
.editorconfig      LICENSE            asdf.sh            help.txt
.git/              README.md          ballad-of-asdf.md  lib/
.github/           SECURITY.md        bin/               lint.sh
.gitignore         VERSION            completions/       release/
CHANGELOG.md       Vagrantfile        defaults           test/
CONTRIBUTING.md    asdf.fish          docs/              
root@05457de92892:~# . .asdf/asdf.sh 
root@05457de92892:~# asdf plugin add haxe https://github.com/arroadie/asdf-haxe
root@05457de92892:~# asdf plugin add neko
initializing plugin repository...
Cloning into '/root/.asdf/repository'...
remote: Enumerating objects: 2224, done.
remote: Total 2224 (delta 0), reused 0 (delta 0), pack-reused 2224
Receiving objects: 100% (2224/2224), 502.74 KiB | 3.35 MiB/s, done.
Resolving deltas: 100% (1000/1000), done.
root@05457de92892:~# echo "haxe 4.1.3" >> .tool-versions
root@05457de92892:~# echo "neko 2.3.0" >> .tool-versions
root@05457de92892:~# asdf install
∗ Downloading Haxe source...
The installation was successful!

If you get dylib errors when running haxelib be sure to read https://github.com/asdf-community/asdf-haxe#troubleshooting
∗ Downloading Neko source...
The installation was successful!
root@05457de92892:~# asdf haxe neko dylibs link
'/root/.asdf/installs/haxe/4.1.3/bin/libneko.so' -> '/root/.asdf/installs/neko/2.3.0/bin/libneko.so'
'/root/.asdf/installs/haxe/4.1.3/bin/libneko.so.2' -> '/root/.asdf/installs/neko/2.3.0/bin/libneko.so.2'
'/root/.asdf/installs/haxe/4.1.3/bin/libneko.so.2.3.0' -> '/root/.asdf/installs/neko/2.3.0/bin/libneko.so.2.3.0'
root@05457de92892:~# haxelib version
4.0.2
root@05457de92892:~# asdf haxe neko dylibs unlink
removed '/root/.asdf/installs/haxe/4.1.3/bin/libneko.so'
removed '/root/.asdf/installs/haxe/4.1.3/bin/libneko.so.2'
removed '/root/.asdf/installs/haxe/4.1.3/bin/libneko.so.2.3.0'
root@05457de92892:~# haxelib version
/root/.asdf/installs/haxe/4.1.3/bin/haxelib: error while loading shared libraries: libneko.so.2: cannot open shared object file: No such file or directory
root@05457de92892:~# haxelib version
4.0.2
root@05457de92892:~# asdf haxe neko dylibs which
4.1.3
root@05457de92892:~#
```

If you're able to shed some light on the reason, please...

**Comment by smorimoto** [comment]
Okay, it should work right now.

**Comment by smorimoto** [comment]
Thanks @arroadie!

**Comment by arroadie** [comment]
All good, thanks for the support!

**Comment by smorimoto** [comment]
Anytime :)

**Pull request merged**
